apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-svcacc
  namespace: dev-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev-frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 4200
    targetPort: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: dev-frontend
    app.kubernetes.io/version: v1
  name: frontend
  namespace: dev-frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend  
    spec:
      containers:
        - name: frontend
          image: louarhou/frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
          - name: web
            containerPort: 4200
            protocol: TCP
      serviceAccountName: frontend-svcacc