apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-svcacc  
  namespace: dev-auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: dev-auth
  labels:
    name: auth
spec:
  type: LoadBalancer # for testing, Not recommended for production
  #type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: dev-auth
    app.kubernetes.io/version: v1
  name: auth
  namespace: dev-auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: louarhou/auth-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:   
            - name: DB_HOST  
              valueFrom:
                configMapKeyRef:
                  name: auth-db-conf
                  key: host
            - name: DB_NAME  
              valueFrom:
                secretKeyRef:
                  name: mysql-db-credentials
                  key: dbname
            - name: DB_USERNAME  
              valueFrom:
                secretKeyRef:
                  name: mysql-db-credentials
                  key: rootname
            - name: DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mysql-db-credentials
                  key: rootpassword
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: auth-service-credentials
                  key: jwt_issuer
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth-service-credentials
                  key: jwt_audience
      serviceAccountName: auth-svcacc  