apiVersion: v1
kind: Secret
metadata:
  name: auth-service-credentials
  namespace: dev-auth
type: Opaque
data:
  jwt_issuer: b3VhcmhvdUByZW1vdGUuY29t    # ouarhou@remote.com
  jwt_audience: b3VhcmhvdUByZW1vdGUuY29t