apiVersion: v1
kind: ServiceAccount
metadata:
  name: repositories-svcacc
  namespace: dev-repositories
---
apiVersion: v1
kind: Service
metadata:
  name: repositories
  namespace: dev-repositories
spec:
  selector:
    app: repositories
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  #type: ClusterIP
  #type: NodePort
  type: LoadBalancer  # for testing, Not recommended for production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: repositories
    app.kubernetes.io/part-of: dev-repositories
    app.kubernetes.io/version: v1
  name: repositories
  namespace: dev-repositories
spec:
  selector:
    matchLabels:
      app: repositories
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: repositories
    spec:
      containers:
        - name: repositories
          image: louarhou/repositories:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      serviceAccountName: repositories-svcacc